#pragma once

#include "preprocessor.h"

#define R               ACCESS_CONTROL_READ
#define RW              ACCESS_CONTROL_READ | ACCESS_CONTROL_WRITE
#define RR              ACCESS_CONTROL_READ | ACCESS_CONTROL_REPORTABLE
#define RWR             ACCESS_CONTROL_READ | ACCESS_CONTROL_WRITE | ACCESS_CONTROL_REPORTABLE

#define CLUSTER_ATTRIBUTE(UCLUSTER, LCLUSTER, TYPE, ACCESS, UNAME, LNAME, INITIAL_VALUE) \
    { PP_CAT4(ZCL_ATTRID_, UCLUSTER, _, UNAME), PP_CAT(ZCL_DATA_TYPE_, TYPE), ACCESS, (u8*)&PP_CAT(zcl_, LCLUSTER).LNAME  },
#define ATTRIBUTE_REVISION \
    { ZCL_ATTRID_GLOBAL_CLUSTER_REVISION,   ZCL_DATA_TYPE_UINT16,     R,  (u8*)&zcl_attr_global_clusterRevision},

#define CLUSTER_FIELD_BITMAP8(NAME) u8 NAME
#define CLUSTER_FIELD_BOOLEAN(NAME) u8 NAME
#define CLUSTER_FIELD_ENUM8(NAME) u8 NAME
#define CLUSTER_FIELD_INT16(NAME) s16 NAME
#define CLUSTER_FIELD_UINT8(NAME) u8 NAME
#define CLUSTER_FIELD_UINT16(NAME) u16 NAME
#define CLUSTER_FIELD_UINT32(NAME) u32 NAME
#define CLUSTER_FIELD_SINGLE_PREC(NAME) float NAME
#define CLUSTER_FIELD_UTC(NAME) u32 NAME
#define CLUSTER_FIELD_CHAR_STR(NAME) u8 NAME[ZCL_BASIC_MAX_LENGTH]

#define CLUSTER_FIELD(TYPE, ACCESS, UNAME, LNAME, INITIAL_VALUE) PP_CAT(CLUSTER_FIELD_, TYPE)(LNAME);

#define CLUSTER_FIELD_INIT(TYPE, ACCESS, UNAME, LNAME, INITIAL_VALUE) .LNAME = INITIAL_VALUE,

#define DECLARE_CLUSTER(UNAME, LNAME, ATTRIBUTES) \
  typedef struct { \
    PP_SEQ_FOR_EACH_UNPACK(CLUSTER_FIELD, ATTRIBUTES) \
  } PP_CAT3(zcl_, LNAME, Attr_t); \
  extern PP_CAT3(zcl_, LNAME, Attr_t) PP_CAT(zcl_, LNAME);

#define DEFINE_CLUSTER(UNAME, LNAME, ATTRIBUTES) \
  PP_CAT3(zcl_, LNAME, Attr_t) PP_CAT(zcl_, LNAME) = { \
    PP_SEQ_FOR_EACH_UNPACK(CLUSTER_FIELD_INIT, ATTRIBUTES) \
  }; \
  const zclAttrInfo_t PP_CAT(LNAME, _attrTbl)[] = { \
    PP_SEQ_FOR_EACH_REPACK(CLUSTER_ATTRIBUTE, (UNAME, LNAME), ATTRIBUTES) \
    ATTRIBUTE_REVISION \
  };

#define CLUSTER(...) DECLARE_CLUSTER(__VA_ARGS__)
